### ISSUE TITLE
Congrats

### ISSUE THREAD

**Issue by chmiiller** [gbaldera/TiTouchGallery#1]
Hey man, congrats for the free module! It helps me soooo muucchh! Works very nice! I really can't understand why it can works with local images, but that's ok! euhehue...
Thank you so much!

**Comment by gbaldera** [comment]
@chmiiller you're welcome, I'm glad that you found it useful. Currently the module only works with remote images, cause I built it to solve that need for the moment and I don't have enough time right now to add support for local files, maybe later :grinning:

**Comment by ghost** [comment]
Hi, still no support for local image?
