### ISSUE TITLE
Errors on Android 6.0 while requiring module with Ti SDK 5.0.2

### ISSUE THREAD

**Issue by fahad86** [gbaldera/TiTouchGallery#10]
java.lang.UnsatisfiedLinkError: dlopen failed:

Solution:
Recompile module with latest NDK

**Comment by fahad86** [comment]
Pull Request: https://github.com/gbaldera/TiTouchGallery/pull/11

**Comment by AppWerft** [comment]
@fahad86:  Do you have a compiled version or patched source tree?

**Comment by fahad86** [comment]
@AppWerft here you go: https://github.com/fahad86/TiTouchGallery/blob/b4d9ce8296e7cd0ca4009fcfeb8ae8e972b289ef/dist/com.gbaldera.titouchgallery-android-1.2.zip

**Comment by WillDent** [comment]
@fahad86 can you update this so Gitt.io picks up the latest version?  Only 1.1 is available.

Thanks

**Comment by fahad86** [comment]
@gbaldera can you merge Pull Request: #11

**Comment by gbaldera** [comment]
@fahad86 @WillDent @AppWerft sorry for my late response. I haven't work on titanium for a long time. I'll be open for requests on taking control of future updates to this project. So if any of you are interested let me know.
